---
title: "Lab 1G - What's the FREQ?"
output: word_document
---


**Directions: Record your responses to the lab questions in the spaces provided.**

\newline

When we're dealing with categorical variables, we can't just calculate an average to describe a _typical_ value.

\newline

\newline

\newline

When trying to describe categorical variables with numbers, we calculate frequency tables

\newline

\newline

\newline

Fill in the blanks below to answer the following: How many more _females_ than _males_ are there in our ATU data??

\newline

\newline

\newline

Does one `gender` seem to have a higher occurence of physical challenges than the other? If so, which one and explain your reasoning?

\newline

\newline

\newline

Does one `gender` seem to have a higher occurence of physical challenges than the other? If so, which one and explain your reasoning?

\newline

\newline

\newline

Did your answer change from before? Why?

\newline

\newline

\newline

Describe what happens if you create a 2-way frequency table with a numerical variable and a categorical variable.

\newline

\newline

\newline

How are the types of statistical questions that 2-way frequency tables can answer different than 1-way frequency tables?

\newline

\newline

\newline

Which gender has a higher rate of _part time employment_?

\newline

\newline

\newline

Does one gender socialize more than the other? To answer this question first:

\newline

\newline

\newline

Create a subset of the ATU data that includes only people who socialized more than 0 minutes.

\newline

\newline

\newline

Create a `histogram` and include `type = "percent"` as an option in the function.
