---
title: "Lab 1E - What's the Relationship?"
output: word_document
---


**Directions: Record your responses to the lab questions in the spaces provided.**

\newline

How many variables were used to create this plot? Which variables were used and how were they used?

\newline

\newline

\newline

Do snacks that have more `calories` also have more `total_fat`? Why do you think that?

\newline

\newline

\newline

What happens if you swap the `calories` and `total_fat` variables in your code? Does the relationship between the variables change?

\newline

\newline

\newline

Does the relationship between `calories` and `total_fat` change when the snack is either `Salty` or `Sweet`? Write down the code you used to answer this question.

\newline

\newline

\newline

Create a scatterplot that uses these 4 variables: `sodium`, `sugar`, `healthy_level`, `salty_sweet`.

\newline

\newline

\newline

How does the `healthy_level` of a `Salty` or `Sweet` snack impact the number of `calories` in the snack?.

\newline

\newline

\newline

Do healthier snacks `cost` more or less than less healthy snacks?

\newline

\newline

\newline

What other variables seem to be related to the `cost` of a snack? Describe their relationships.
