---
title: "Lab 1B - Get the picture?"
output: word_document
---


**Directions: Record your responses to the lab questions in the spaces provided.**

\newline

Is `height` a numerical or categorical variable? Why?

\newline

\newline

\newline

Is `gender` a numerical or categorical variable? Why?

\newline

\newline

\newline

List either the different categories or what you think the measured units are for `height` and `gender`.

\newline

\newline

\newline

Write down 3 variables that you think are _categorical_ variables and why.

\newline

\newline

\newline

Write down 3 variables that you think are _numerical_ variables and why.

\newline

\newline

\newline

List all the types of info the `str()` function outputs

\newline

\newline

\newline

Were you able to correctly guess which variables were categorical and numeric? Which ones did you mis-label?

\newline

\newline

\newline

Which function, either `bargraph` or `histogram` is better at visualizing categorical variables? Which is better at visualizing numerical variables?

\newline

\newline

\newline

What does the y-axis represent?

\newline

\newline

\newline

What does the x-axis tell us?

\newline

\newline

\newline

Would you say that _most_ people _never_ texted while driving? What does the word _most_ mean?

\newline

\newline

\newline

Approximately what percent of the people texted while driving for 20 or more days? (Hint: There's 15,624 students in our data.

\newline

\newline

\newline

Write a sentence explaining how boys and girls differ in their use texting while driving.

\newline

\newline

\newline

Would you say that most girls never text and drive?  Would you say that most boys never text and drive?

\newline

\newline

\newline

How did including the `groups` argument in your code change the graph?

\newline

\newline

\newline

Can you use this graphic to answer the question at the top of the slide? Why or why not?

\newline

\newline

\newline

Is grouping numeric values, such as heights, as helpful as grouping categorical variables, such as texting & driving?

\newline

\newline

\newline

Why does this work for bargraphs but not for for histograms?

\newline

\newline

\newline

Do you think males & females have similar heights? Use the plot you create to justify your answer.

\newline

\newline

\newline

Just like we did for the histogram, is it possible to create a _split_ bargraph? Try to create a bargraph of `drive_text` that's split by `gender` to find out.

\newline

\newline

\newline

What other factors do you think might affect how often people text and drive?

\newline

\newline

\newline

Choose one variable from the `cdc` data, make a graph, and use the graph to describe how `drive_text` use differs with this variable.
