---
title: "Lab 2B - Oh the Summaries ..."
output: word_document
---


**Directions: Record your responses to the lab questions in the spaces provided.**

\newline

Which of the color scores had the smallest `min` value? Which had the largest `max` value?

\newline

\newline

\newline

Use the `range` function to calculate the `max` and `min` values of your predominant color

\newline

\newline

\newline

Use these two steps to calculate the _range_ of your predominant color.

\newline

\newline

\newline

Which of the four colors has the largest absolute difference between the `mean` and `median` values?

\newline

\newline

\newline

By examining a `dotPlot` for this personality color, make an argument why either the `mean` or `median` would be the better description of the _center_ of the data.

\newline

\newline

\newline

Use a `dotPlot` or `histogram` to find the personality color with the largest difference between the `max` and `min` values. Then use the `Range` function you created to calculate its _range_.

\newline

\newline

\newline

Use a similar line of code to calculate _Q3_, which is the value that's larger than 75% of our data.

\newline

\newline

\newline

Write down the numbers that split the data up into these 4 pieces.

\newline

\newline

\newline

How long is the interval of the middle two pieces?

\newline

\newline

\newline

Use the values of _Q1_ and _Q3_ you calculated previously and find the _IQR_ by hand.

\newline

\newline

\newline

Then use the `iqr()` function to calculate it for you.

\newline

\newline

\newline

Which personality color score has the widest spread according to the _IQR_? Which is narrowest?

\newline

\newline

\newline

By showing someone a `dotPlot`, how would you teach them to make a _boxplot_? Write out your explanation in a series of steps for the person to use.

\newline

\newline

\newline

Use the steps you write to create a sketch of a _boxplot_ for your predominant color's scores in your journal.

\newline

\newline

\newline

Then use the `bwplot` function to create a _boxplot_ using `R`.

\newline

\newline

\newline

Create a function called `myIQR` that uses the _only_ `quantile` function to compute the middle 30% of the data.
