---
title: " - Which song plays next?"
output: word_document
---


**Directions: Record your responses to the lab questions in the spaces provided.**

\newline

Why do we _put a song back_ each time we make a selection? 

\newline

\newline

\newline

What would happen in our little experiment if we did not do this?  

\newline

\newline

\newline

Once everyone in your class has computed their proportions, calculate the _range_ of proportions (The largest proportion minus the smallest proportion) for your class and write it down.

\newline

\newline

\newline

Compute the proportion of `"rap"` songs for your 50 draws and find out if the _range_ for your class' proportions is bigger or smaller than when we drew 10 songs.

\newline

\newline

\newline

Are the proportions still the same? If so, can you find two different values for `set.seed` that give different answers?

\newline

\newline

\newline

Answer this by estimating the probability that a randomly chosen student went to the movies using 500 simulations.

\newline

\newline

\newline

Write down both the estimated probability and the code you used to compute your estimate. You might find it helpful to write your answer in an R Script _(File -> New File -> R Script)_

\newline

\newline

\newline

Include `set.seed(123)` in your code before you `do` 500 repeated samples.
