---
title: "Lab 2E - The Horror Movie Shuffle"
output: word_document
---


**Directions: Record your responses to the lab questions in the spaces provided.**

\newline

How many variables and observations are contained in the data and what are the possible values of the variables?

\newline

\newline

\newline

Which gender had more survivors? Write down a few sentences as to how you came to your conclusion. Be sure to look at both the _counts_ and _proportion_ of survivors before deciding.

\newline

\newline

\newline

Calculate the difference between the proportion of females who survived and the proportion of males who survived. Is the difference large enough to conclude that women tend to survive more often than men?

\newline

\newline

\newline

The last question on the previous slide can be answered using the 2nd line of code. Why?

\newline

\newline

\newline

How many people survived, in total, the slasher film before shuffling? How many people survived after shuffling?

\newline

\newline

\newline

How has shuffling our data changed the proportion of women who survived compared to men who survived?

\newline

\newline

\newline

Is the difference in proportions from your shuffled data larger or smaller than the difference from the original data? Interpret what this means.

\newline

\newline

\newline

Explain why shuffling our data one time is not enough to decide if the difference seen in our _actual_ data occurs by chance or not.

\newline

\newline

\newline

`View` your shuffled data and explain what the rows and each column represents.

\newline

\newline

\newline

For the first row of shuffled data in the `shuffles`, what is the difference between proportion of females who survived and the proportion of males who survived?

\newline

\newline

\newline

What was the typical difference in proportions between men and women survivors?

\newline

\newline

\newline

Locate the value of the _actual_ difference in the plot. Does the actual difference occur very often by chance alone?

\newline

\newline

\newline

Does `gender` play a role in whether or not a character will survive in a horror film? Explain your reasoning.

\newline

\newline

\newline

If you wanted to survive in a horror film, would you want to play a female character or a male character?

\newline

\newline

\newline

Does shuffling the `gender` variable instead of the `survival` variable change your answer to the question _Does `gender` play a role in whether or not a character will survive in a horror film?_

\newline

\newline

\newline

Why or why not?
