---
title: "Lab 2H - Eyeballing Normal"
output: word_document
---


**Directions: Record your responses to the lab questions in the spaces provided.**

\newline

Which part of the normal curve changes when the value of the `mean` changes?

\newline

\newline

\newline

Which part of the normal curve changes when the value of the `sd` changes?

\newline

\newline

\newline

Based on what you know about these variables, which of the variables do you think have distributions that will look like the normal distribution?

\newline

\newline

\newline

Make histograms of these variables.  Which ones look like the normal distribution?

\newline

\newline

\newline

For each of the following, determine which, if any, appear to be normally distributed. Explain your reasoning:

\newline

\newline

\newline

The `weight` of people in our `cdc` data, faceted by `gender`.

\newline

\newline

\newline

The difference in `mean` weights between `Male`s and `Female`s for 500 random shuffles.

\newline

\newline

\newline

The difference in `median` weights between `Male`s and `Female`s for 500 random shuffles.
