---
title: "Lab 3D - Are you sure about that?"
output: word_document
---


**Directions: Record your responses to the lab questions in the spaces provided.**

\newline

The United States has an estimated population of 327,350,075. How many people were surveyed for this particular data set?

\newline

\newline

\newline

Why is it important that the ATUS is a random sample?

\newline

\newline

\newline

Use our `atus` data to calculate an estimate for the average age of people older than 15 living in the U.S.

\newline

\newline

\newline

Write a paragraph that explains to someone that's not familiar with `R` how you created `bs_rows` and `bs_atus`. Be sure to include an explanation of what the _values_ of `bs_rows` mean and how those values are used to create `bs_atus`. Also, be sure to explain what each argument of each function does.

\newline

\newline

\newline

Create a histogram for your bootstrapped samples and describe the _center_, _shape_ and _spread_ of its distribution.

\newline

\newline

\newline

Using your histogram, fill in the statement below:

\newline

\newline

\newline

Based on your bootstrapped estimates, between which two ages are we 90% confident the actual mean age of people living in the U.S. is contained?

\newline

\newline

\newline

Why is the 95% confidence interval wider than the 90% interval?

\newline

\newline

\newline

Write down how you would explain what a 95% confidence interval means to someone not taking _Introduction to Data Science_.
