---
title: "Lab 3C - Random Sampling"
output: word_document
---


**Directions: Record your responses to the lab questions in the spaces provided.**

\newline

Write down two reasons why getting _everyone_ in Los Angeles to fill out the survey would be difficult. Also, write a sentence why the DWP might consider using a sample of households instead.

\newline

\newline

\newline

Why do you think we call this method a _convenience_ sample?

\newline

\newline

\newline

Do you think the distribution of `grade` for your sample would look similar when compared to the whole `cdc` data?

\newline

\newline

\newline

Which groups of people do you think are over or under represented in your convenience sample? Why?

\newline

\newline

\newline

Compare the distributions of the `cdc` data and your convenience sample and write down how they differ.

\newline

\newline

\newline

Write a sentence that explains why you think the distribution of `grade` for this _random sample_ will look more or less similar to the distribution from the whole `cdc` data.

\newline

\newline

\newline

How do the distributions change as the size of the sample increases? Why do you think this occurs?

\newline

\newline

\newline

Which set of proportions looks most similar to the proportions of the population?

\newline

\newline

\newline

Write down a reason why estimates based on _convenience_ samples might not improve even as sample size increases.
