---
title: "Lab 4D - Interpreting correlations"
output: word_document
---


**Directions: Record your responses to the lab questions in the spaces provided.**

\newline

Are these variables linearly related? Why or why not?

\newline

\newline

\newline

Does this plot have a positive or negative correlation?

\newline

\newline

\newline

Recall that if there is no linear relation between two numerical variables, the correlation coefficient is close to 0. What do you guess the correlation coefficient will be for these two variables?

\newline

\newline

\newline

Calculate the correlation coefficient for these variables using the `cor` function. The inputs to the functions work just like the inputs of the `xyplot` function.

\newline

\newline

\newline

What was the value of the correlation coefficient you calculated?

\newline

\newline

\newline

How does this actual value compare with the one you estimated previously?

\newline

\newline

\newline

Does this indicate a strong, weak, or moderate association? Why?

\newline

\newline

\newline

How would the scatter plot need to change in order for the correlation to be stronger?

\newline

\newline

\newline

How would it need to change in order for the correlation to be weaker?

\newline

\newline

\newline

<!-- - Would the correlation coefficient change if we took all of our values and subtracted 50 from all of the `critics_score`? Why do you think this is? -->

\newline

\newline

\newline

<!-- - What value was returned for the correlation coefficient? -->

\newline

\newline

\newline

<!-- - How does this actual value compare with the one you estimated previously? -->

\newline

\newline

\newline

<!-- - What happens to the correlation coefficient if we multiplied all of the `critics_rating` values by 50?  How do you explain this? -->

\newline

\newline

\newline

<!-- - What value was returned for the correlation coefficient? -->

\newline

\newline

\newline

<!-- - How does this actual value compare with the one you estimated previously? -->

\newline

\newline

\newline

Use the correlation coefficient to determine which variable has a stronger linear relationship with `critics_rating`.

\newline

\newline

\newline

Use the MSE to determine which variable is a better predictor of `critics_rating`.

\newline

\newline

\newline

How are the correlation coefficient and the MSE related?

\newline

\newline

\newline

Would calculating a correlation coefficient for the two variables be appropriate. Justify your answer.

\newline

\newline

\newline

Predict what value you think the correlation coefficient will be. Compare this value to the actual value. Finally, interpret what the actual correlation coefficient means.

\newline

\newline

\newline

Why do you think these variables are so strongly related? Is using the correlation coefficient to describe the relationship appropriate and why/why not?
