---
title: "Lab 4A - If the line fits ..."
output: word_document
---


**Directions: Record your responses to the lab questions in the spaces provided.**

\newline

If you had to predict the height of someone in the LA area, what single height would you choose and why?

\newline

\newline

\newline

Would you describe this as a _good_ guess? What might you try and improve your predictions?

\newline

\newline

\newline

What `height` would you predict if you knew a person had an `armspan` around 62 inches?

\newline

\newline

\newline

What `height` would you predict if you knew a person had an `armspan` around 65 inches?

\newline

\newline

\newline

Does knowing someone's `armspan` helps you predict their height. Why or why not?

\newline

\newline

\newline

<!--     - How much taller is the person with a 70 inch `armspan` than the 69 inch `armspan`, on average? Does this seem reasonable? -->

\newline

\newline

\newline

<!--     - How tall would you predict someone who had a 69.5 inch `armspan` to be? -->

\newline

\newline

\newline

Predict how tall a person with a 62 and a person with a 65 inch `armspan` would be.

\newline

\newline

\newline

<!-- - How much taller is the person with a 70 inch `armspan` than the 69 inch `armspan`? Does this difference seem more reasonable than the difference we calculated using the means?   -->

\newline

\newline

\newline

How tall would you predict a person with a 63.5 inch `armspan` to be?

\newline

\newline

\newline

Compare your answers with a neighbor's. Did both of you come up with the same equation for a line? If not, can you tell which line fits the data best?

\newline

\newline

\newline

Measure your `armspan` and use the regression line to predict your height. How close was the prediction?
