---
title: "Lab 4G - Growing trees"
output: word_document
---


**Directions: Record your responses to the lab questions in the spaces provided.**

\newline

Why can't we just use a _linear model_ to predict whether a passenger on the Titanic `survived` or not based on their `gender`?

\newline

\newline

\newline

Write down the labels of the two _branches_.

\newline

\newline

\newline

Write down the labels of the two _leaves_.

\newline

\newline

\newline

Which `gender` does the model predict will survive?

\newline

\newline

\newline

Where does the plot tell you the number of people that get sorted into each leaf? How do you know?

\newline

\newline

\newline

Where does the plot tell you the number of people that have been sorted _incorrectly_ in each leaf?

\newline

\newline

\newline

Mrs. Cumings was a 38 year old female with a 1st class ticket from Cherbourg. Does the model predict that she survived?

\newline

\newline

\newline

Which variable ended up not being used by `tree`?

\newline

\newline

\newline

How is `tree3` different from `tree2`?

\newline

\newline

\newline

In your own words, explain what the _misclassification rate_ is.

\newline

\newline

\newline

Which model (`tree1`, `tree2` or `tree3`) had the lowest misclassification rate for the `titanic_test` data?

\newline

\newline

\newline

Does creating a more complex _classification tree_ always lead to better predictions? Why not?
